### ISSUE TITLE
Jest fail to collect untested files coverage

### ISSUE THREAD

**Issue by coolbeatz71** [andela/ah-kgl-wakanda-frontend#26]
Hey! After rebasing from `develop` , I realized that `jest` started taking a lot of time in order to collect coverage from untested files. Sometimes it is even failing to collect coverage. It is really preventing me from raising a Pull Request.

We need to fix it.

**Comment by coolbeatz71** [comment]
> Hey! After rebasing from `develop` , I realized that `jest` started taking a lot of time to collect coverage from untested files. Sometimes it is even failing to collect coverage.
> 
> We need to fix it.

After debugging. I found it was a problem of some chunk files which are mysteriously hidden inside `assets/images/`.

**Comment by coolbeatz71** [comment]
> > Hey! After rebasing from `develop` , I realized that `jest` started taking a lot of time to collect coverage from untested files. Sometimes it is even failing to collect coverage.
> > We need to fix it.
> 
> After debugging. I found the issue was probably caused by some chunk files which are mysteriously hidden inside `assets/images/`.

**Comment by gracelungu** [comment]
@coolbeatz71 How did you solve the problem then?

**Comment by dkam26** [comment]
@coolbeatz71 ,Can you raise a PR to fix the issue on develop?

**Comment by coolbeatz71** [comment]
> @coolbeatz71 ,Can you raise a PR to fix the issue on develop?
I solved it by removing the mysterious folder `src/assets/images/React App_files` that were mistakenly pushed. And probably tell Jest to ignore the folder when collecting coverage.

https://github.com/andela/ah-kgl-wakanda-frontend/commit/bfaf6e8ef9b9d77cbd04e71db839122930243351 fixes the issue
